# -*- coding: utf-8 -*-
"""text2sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7cPHaOaZs82pLmhAJ-XhGb3U1plt6Rm
"""

!pip install --quiet --upgrade openai duckdb pandas matplotlib

from openai import OpenAI
import duckdb
import pandas as pd
import matplotlib.pyplot as plt
import getpass
import re

client = OpenAI(api_key=getpass.getpass("Enter your OpenAI API key: "))

import kagglehub

# Download latest version
path = kagglehub.dataset_download("umuttuygurr/e-commerce-customer-behavior-and-sales-analysis-tr")
print("Path to dataset files:", path)

df = pd.read_csv(f"{path}/ecommerce_customer_behavior_dataset.csv")
print("Rows:", len(df))
df.head(3)

#Load table to DuckDB
con = duckdb.connect(database=':memory:')
con.execute("CREATE TABLE orders AS SELECT * FROM df")
con.sql("SELECT * from orders limit 5").df()

##LLM Section
# Format the returned query
def fix_duckdb_sql(sql: str) -> str:
    """
    Cleans and corrects common LLM SQL formatting issues for DuckDB.
    Handles:
      - UNION / UNION ALL wrapping
      - misplaced 'ALL' tokens
      - trailing semicolons
      - stray English text or comments
    """
    # Remove English explanations accidentally included by model
    sql = re.sub(r'(?i)(^to\s|get\s|return\s).*', '', sql)

    # Fix "UNION (ALL SELECT" -> "UNION ALL (SELECT"
    sql = re.sub(r'UNION\s*\(\s*ALL', 'UNION ALL (', sql, flags=re.IGNORECASE)

    # Fix cases where ALL is misplaced
    sql = sql.replace("UNION ( ALL", "UNION ALL (")
    sql = sql.replace("UNION( ALL", "UNION ALL (")

    # Ensure subqueries around UNIONs are parenthesized
    if "UNION" in sql.upper():
        parts = re.split(r'\bUNION(?: ALL)?\b', sql, flags=re.IGNORECASE)
        union_tokens = re.findall(r'\bUNION(?: ALL)?\b', sql, flags=re.IGNORECASE)
        wrapped_parts = []
        for p in parts:
            p = p.strip().rstrip(";")
            if not (p.startswith("(") and p.endswith(")")):
                p = f"(\n{p}\n)"
            wrapped_parts.append(p)
        # Reassemble correctly
        sql = " ".join(
            f"{wrapped_parts[i]} {union_tokens[i]}" if i < len(union_tokens) else wrapped_parts[i]
            for i in range(len(wrapped_parts))
        )

    # Remove any stray trailing semicolon
    sql = sql.strip().rstrip(";")

    return sql.strip()

# Text → SQL translator
def text_to_sql(user_query, table_schema):
    prompt = f"""
You are an expert SQL analyst. Use the conversation history and the user's question
to generate a valid DuckDB SQL query on the 'orders' table.

Rules:
- Return ONLY SQL (no markdown, no explanation)
- Always cast date/time strings before using date functions, e.g., CAST(Date AS TIMESTAMP)
- When displaying currency fields (like Total_Amount, Sales, Revenue, or similar),
  limit it to 2 decimals
- Do not use CTE For a simple query lets say finding the total count & sum
- Use CTEs (WITH ... AS) ONLY when:
  - A direct query is not possible, or
  - You need to reference the same data multiple times in the query, or
  - You need multiple layers of aggregation (aggregation over aggregation), or
  - When asked to find the "highest" or "maximum" per group (e.g., best-selling day for each product),
    generate a query that returns only that row per group, using WHERE ... IN (SELECT ... MAX(...) GROUP BY ...),
    not all intermediate results.
- Always generate DuckDB-compliant syntax.

- Use columns:
{schema}
User question: "{user_query}"

SQL:
"""
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    # Clean output — remove markdown if any
    sql_query = response.choices[0].message.content.strip()
    sql_query_refined = fix_duckdb_sql(sql_query)

    return sql_query_refined

schema = con.sql("DESCRIBE orders").df().to_string(index=False)
print(schema)

#Chatbot logic
def chatbot(query):
    print(f"🔹 User: {query}")
    sql_query = text_to_sql(query, schema)
    print(f"\n🧠 Generated SQL:\n{sql_query}")
    try:
        result = con.sql(sql_query).df()
        display(result)
    except Exception as e:
        print("⚠️ Error executing SQL:", e)

chatbot("what is the total count of orders & sales amount for each category. provide only the top 5 sale amount")

chatbot("What are the top 5 regions based on sales amount")

chatbot("what payment mode has the largest preference?")

#Lets validate the results by running the query manually

chatbot("Which day of the week has the highest sales for each product")

chatbot("What is the return rate % per category? I want the results in desc order")

chatbot("Provide the top 5 products along with its order details with poor ratings (<3) ?")

chatbot(" Which device is most preffered by customers for placing orders?")

#Validation
# Try running the query in the below format to cross verify the results

con.sql("""
 SELECT
        Payment_Method,
        COUNT(*) AS Payment_Count
    FROM
        orders
    GROUP BY
        Payment_Method
        """)

